name: Intel
description: File a new intel report
title: "[Intel]: "
labels: ["new", "confirmed", "deprecated"]
assignees:
  - timb-machine
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit this intel.
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Select what area of Linux malware research this affects 
      multiple: false
      options:
        - Press/academia
        - Breach reports
        - Supply chain attacks
        - Malware reports
        - Malware binaries
        - Malware source
        - Malware PoCs
        - Offensive tools
        - Offensive techniques
        - Defensive tools
        - Defensive techniques
        - Defensive Yara
  - type: dropdown
    id: parent_threat
    attributes:
      label: Parent threat
      description: Select what parent (ATT&CK technique) threat this relates to 
      multiple: true
      options:
        - Reconnaissance
        - Resource Development
        - Initial Access
        - Execution
        - Persistence
        - Privilege Escalation
        - Defense Evasion
        - Credential Access
        - Discovery
        - Lateral Movement
        - Collection
        - Command and Control
        - Exfiltration
        - Impact
  - type: textarea
    id: finding
    attributes:
      label: Finding
      description: Add any URLs to public references to the threat
      placeholder: https://...
    validations:
      required: false
  - type: textarea
    id: industry_reference
    attributes:
      label: Industry reference
      description: CWE/ATT&CK/Actor etc reference
  - type: textarea
    id: malware_reference
    attributes:
      label: Malware reference
      description: Family/hash etc reference
  - type: textarea
    id: actor_reference
    attributes:
      label: Actor reference
      description: Actor/campaign etc reference
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Select what component this affects 
      multiple: true
      options:
        - Linux
        - AIX
        - Solaris
        - HP-UX
        - IOT
        - Banking
        - CNI
        - Telecomms
        - Hosting
        - Industrial
        - Other
  - type: dropdown
    id: scenario
    attributes:
      label: Scenario
      description: Select what scenario this affects 
      multiple: true
      options:
        - Consumer
        - Cloud hosted services
        - Internal enterprise services
        - Internal specialist services
        - Enterprise with satellite facilities
        - Multi-cloud/Cloud-to-cloud enterprise
        - Enterprise with contracted services and/or non-employee access
        - Collaboration across enterprise boundaries
        - Enterprise with public/Customer-facing services
